# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.19.0
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run install (rpc)
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd ./src/rpc_client-src install # will run `yarn install` command
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: release:prod # will run `yarn release:prod` command
          
     # - name: Zip artifact for deployment
     #   run: Compress-Archive -Path ./dist/com.tee.discord-rpc -Destination ./discord.rpc.zip
      - name: Create folder (com.tee.discord-rpc)
        run: New-Item -Path "./" -Name "com.tee.discord-rpc" -ItemType "directory"
      - name: Move artifact from dist
        run: Move-Item -Path "./dist/com.tee.discord-rpc" -Destination "./com.tee.discord-rpc"

      - name: Upload artifact for deployment job (zip)
        uses: actions/upload-artifact@v3
        with:
          name: ZIP Release
          path: ./com.tee.discord-rpc
          
      - name: Upload artifact for deployment job (zxp)
        uses: actions/upload-artifact@v3
        with:
          name: ZXP Release
          path: ./dist/com.tee.discord-rpc.zxp
